# Generated by Django 3.2.6 on 2023-01-13 00:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(users.models.UserRoles['USER'], 'user'), (users.models.UserRoles['ADMIN'], 'admin')], max_length=5),
        ),
    ]
